### PR TITLE
Update patch to apply on strace-5.19

### LINKED ISSUE #6: Update patches to 5.19
The patches no longer apply to 5.19. It would be super cool if you could update them.

### PR DESCRIPTION
**Pull request by Ma27**
Closes #6

### CODE REVIEW

**Review by SuperSandro2000 — APPROVED** [review]
Thanks! works

**Comment by Ma27** [comment]
cc @xfgusta

**Comment by xfgusta** [comment]
Thanks @Ma27 and @SuperSandro2000 for contributing. Sorry for the delay, I was away from my computer for a few weeks.

**Review by xfgusta — APPROVED** [review]
Looks good.

**Pull request merged**
